
package cn.ihuyi._106;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "sms", targetNamespace = "http://106.ihuyi.cn/", wsdlLocation = "http://106.ihuyi.cn/webservice/sms.php?WSDL")
public class Sms
    extends Service
{

    private final static URL SMS_WSDL_LOCATION;
    private final static WebServiceException SMS_EXCEPTION;
    private final static QName SMS_QNAME = new QName("http://106.ihuyi.cn/", "sms");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://106.ihuyi.cn/webservice/sms.php?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SMS_WSDL_LOCATION = url;
        SMS_EXCEPTION = e;
    }

    public Sms() {
        super(__getWsdlLocation(), SMS_QNAME);
    }

    public Sms(WebServiceFeature... features) {
        super(__getWsdlLocation(), SMS_QNAME, features);
    }

    public Sms(URL wsdlLocation) {
        super(wsdlLocation, SMS_QNAME);
    }

    public Sms(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SMS_QNAME, features);
    }

    public Sms(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Sms(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SmsSoap
     */
    @WebEndpoint(name = "smsSoap")
    public SmsSoap getSmsSoap() {
        return super.getPort(new QName("http://106.ihuyi.cn/", "smsSoap"), SmsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SmsSoap
     */
    @WebEndpoint(name = "smsSoap")
    public SmsSoap getSmsSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://106.ihuyi.cn/", "smsSoap"), SmsSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SMS_EXCEPTION!= null) {
            throw SMS_EXCEPTION;
        }
        return SMS_WSDL_LOCATION;
    }

}
