
package cn.ihuyi._106;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "smsSoap", targetNamespace = "http://106.ihuyi.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SmsSoap {


    /**
     * 提交短信:<br>参数说明:<br>account:账号<br>password:密码<br>mobile:手机号码<br>content:短信内容
     * 
     * @param password
     * @param mobile
     * @param account
     * @param content
     * @return
     *     returns cn.ihuyi._106.SubmitResult
     */
    @WebMethod(operationName = "Submit", action = "http://106.ihuyi.cn/Submit")
    @WebResult(name = "SubmitResult", targetNamespace = "http://106.ihuyi.cn/")
    @RequestWrapper(localName = "Submit", targetNamespace = "http://106.ihuyi.cn/", className = "cn.ihuyi._106.Submit")
    @ResponseWrapper(localName = "SubmitResponse", targetNamespace = "http://106.ihuyi.cn/", className = "cn.ihuyi._106.SubmitResponse")
    public SubmitResult submit(
        @WebParam(name = "account", targetNamespace = "http://106.ihuyi.cn/")
        String account,
        @WebParam(name = "password", targetNamespace = "http://106.ihuyi.cn/")
        String password,
        @WebParam(name = "mobile", targetNamespace = "http://106.ihuyi.cn/")
        String mobile,
        @WebParam(name = "content", targetNamespace = "http://106.ihuyi.cn/")
        String content);

    /**
     * 修改短信账号密码:<br>参数说明:<br>account:账号<br>password:旧密码<br>newpassword:新密码
     * 
     * @param password
     * @param newpassword
     * @param account
     * @return
     *     returns cn.ihuyi._106.ChangePasswordResult
     */
    @WebMethod(operationName = "ChangePassword", action = "http://106.ihuyi.cn/ChangePassword")
    @WebResult(name = "ChangePasswordResult", targetNamespace = "http://106.ihuyi.cn/")
    @RequestWrapper(localName = "ChangePassword", targetNamespace = "http://106.ihuyi.cn/", className = "cn.ihuyi._106.ChangePassword")
    @ResponseWrapper(localName = "ChangePasswordResponse", targetNamespace = "http://106.ihuyi.cn/", className = "cn.ihuyi._106.ChangePasswordResponse")
    public ChangePasswordResult changePassword(
        @WebParam(name = "account", targetNamespace = "http://106.ihuyi.cn/")
        String account,
        @WebParam(name = "password", targetNamespace = "http://106.ihuyi.cn/")
        String password,
        @WebParam(name = "newpassword", targetNamespace = "http://106.ihuyi.cn/")
        String newpassword);

    /**
     * 查询账户余额:<br>参数说明:<br>account:查询用户名<br>password:查询用户密码
     * 
     * @param password
     * @param account
     * @return
     *     returns cn.ihuyi._106.GetNumResult
     */
    @WebMethod(operationName = "GetNum", action = "http://106.ihuyi.cn/GetNum")
    @WebResult(name = "GetNumResult", targetNamespace = "http://106.ihuyi.cn/")
    @RequestWrapper(localName = "GetNum", targetNamespace = "http://106.ihuyi.cn/", className = "cn.ihuyi._106.GetNum")
    @ResponseWrapper(localName = "GetNumResponse", targetNamespace = "http://106.ihuyi.cn/", className = "cn.ihuyi._106.GetNumResponse")
    public GetNumResult getNum(
        @WebParam(name = "account", targetNamespace = "http://106.ihuyi.cn/")
        String account,
        @WebParam(name = "password", targetNamespace = "http://106.ihuyi.cn/")
        String password);

    /**
     * 查询用户回复:<br>参数说明:<br>account:查询用户名<br>password:查询用户密码
     * 
     * @param password
     * @param account
     * @return
     *     returns cn.ihuyi._106.GetReplyResult
     */
    @WebMethod(operationName = "GetReply", action = "http://106.ihuyi.cn/GetReply")
    @WebResult(name = "GetReplyResult", targetNamespace = "http://106.ihuyi.cn/")
    @RequestWrapper(localName = "GetReply", targetNamespace = "http://106.ihuyi.cn/", className = "cn.ihuyi._106.GetReply")
    @ResponseWrapper(localName = "GetReplyResponse", targetNamespace = "http://106.ihuyi.cn/", className = "cn.ihuyi._106.GetReplyResponse")
    public GetReplyResult getReply(
        @WebParam(name = "account", targetNamespace = "http://106.ihuyi.cn/")
        String account,
        @WebParam(name = "password", targetNamespace = "http://106.ihuyi.cn/")
        String password);

    /**
     * 查询发送回执:<br>参数说明:<br>smsid:流水号
     * 
     * @param smsid
     * @return
     *     returns cn.ihuyi._106.QueryResult
     */
    @WebMethod(operationName = "Query", action = "http://106.ihuyi.cn/Query")
    @WebResult(name = "QueryResult", targetNamespace = "http://106.ihuyi.cn/")
    @RequestWrapper(localName = "Query", targetNamespace = "http://106.ihuyi.cn/", className = "cn.ihuyi._106.Query")
    @ResponseWrapper(localName = "QueryResponse", targetNamespace = "http://106.ihuyi.cn/", className = "cn.ihuyi._106.QueryResponse")
    public QueryResult query(
        @WebParam(name = "smsid", targetNamespace = "http://106.ihuyi.cn/")
        String smsid);

    /**
     * 版本信息,仅用于提示:<br>参数说明:
     * 
     * @return
     *     returns cn.ihuyi._106.VersionInfoResult
     */
    @WebMethod(operationName = "VersionInfo", action = "http://106.ihuyi.cn/VersionInfo")
    @WebResult(name = "VersionInfoResult", targetNamespace = "http://106.ihuyi.cn/")
    @RequestWrapper(localName = "VersionInfo", targetNamespace = "http://106.ihuyi.cn/", className = "cn.ihuyi._106.VersionInfo")
    @ResponseWrapper(localName = "VersionInfoResponse", targetNamespace = "http://106.ihuyi.cn/", className = "cn.ihuyi._106.VersionInfoResponse")
    public VersionInfoResult versionInfo();

}
